apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "thischart.fullname" . }}-ingress
  labels:
    app: {{ template "thischart.name" . }}
    chart: {{ template "thischart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # Good for keeping websockets connected for longer
    #
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
   rules:
    - host: {{ .Values.web.host }}
      http:
         paths:
          - path: /
            backend:
               serviceName: {{ template "thischart.fullname" . }}-web
               servicePort: 80
          - path: /[[ .Name ]]
            backend:
               serviceName: {{ template "thischart.fullname" . }}-ws
               servicePort: 80
   tls:
    - hosts:
      - {{ .Values.web.host }}
