apiVersion: v1
kind: Service
metadata:
  name: {{ template "todo.fullname" . }}-ws
  labels:
    app: {{ template "todo.name" . }}
    chart: {{ template "todo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ template "todo.name" . }}-[[ .Name ]]-ws
    release: {{ .Release.Name | quote }}
