apiVersion: v1
kind: Service
metadata:
  name: {{ template "thischart.fullname" . }}
  labels:
    polaris-project: [[ .Project ]]
    polaris-component: [[ .Component ]]
    app: {{ template "thischart.name" . }}
    chart: {{ template "thischart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ template "thischart.name" . }}
    release: {{ .Release.Name | quote }}
