
resource_name: [[ .Component ]]

replicas: 3

deployment:
  auto: true
  match_semver: ">=0.0.0"

image:
  repository: polaris://[[ .Project ]]-[[ .Component ]]
  tag: 1.0.0
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: "256Mi"
  limits:
    cpu: 200m
    memory: "512Mi"