
buildpipeline:
  codecommitrepo: [[ .Project ]]
  branch: master

web:
  replicas: 1
  host: [[ .Project ]].[[ .Parameters.cluster_name ]]
  ci:
    dockerfilelocation: images/[[ .Project ]]-web
    containerrepository: [[ .Project ]]-web
    tag: 1.0.0
  image:
    repository: [[ .Parameters.aws_account ]].dkr.ecr.[[ .Parameters.aws_region ]].amazonaws.com/[[ .Project ]]-web
    tag: 1.0.0
    pullPolicy: Always

services:
  [[ .Project ]]-ws:
    replicas: 1
    ci:
      dockerfilelocation: images/[[ .Project ]]-ws
      containerrepository: [[ .Project ]]-ws
      tag: 1.0.0
    image:
      repository: [[ .Parameters.aws_account ]].dkr.ecr.[[ .Parameters.aws_region ]].amazonaws.com/[[ .Project ]]-ws
      tag: 1.0.0
      pullPolicy: Always
    env:
      {}

resources:
  requests:
    cpu: 500m
    memory: "768Mi"
  limits:
    cpu: 1000m
    memory: "1024Mi"

nodeSelector: {}

tolerations: []

affinity: {}