
{{- $aws_account  := [[ .Parameters.aws_account ]] }}
{{- $aws_region   := [[ .Parameters.aws_region ]] }}
{{- $cluster_name := [[ .Parameters.cluster_name ]] }}
{{- $application_name := [[ .Name ]] }}

buildpipeline:
  codecommitrepo: {{ $application_name }}
  branch: master

web:
  replicas: 1
  host: {{ $application_name }}.{{ $cluster_name }}
  ci:
    dockerfilelocation: images/{{ $application_name }}-web
    containerrepository: {{ $application_name }}-web
    tag: 1.0.0
  image:
    repository: {{ $aws_account }}.dkr.ecr.{{ $aws_region }}.amazonaws.com/{{ $application_name }}-web
    tag: 1.0.0
    pullPolicy: Always

services:
  {{ $application_name }}-ws:
    replicas: 1
    ci:
      dockerfilelocation: images/{{ $application_name }}-ws
      containerrepository: {{ $application_name }}-ws
      tag: 1.0.0
    image:
      repository: {{ $aws_account }}.dkr.ecr.{{ $aws_region }}.amazonaws.com/{{ $application_name }}-ws
      tag: 1.0.0
      pullPolicy: Always
    env:
      {}

resources:
  requests:
    cpu: 500m
    memory: "768Mi"
  limits:
    cpu: 1000m
    memory: "1024Mi"

nodeSelector: {}

tolerations: []

affinity: {}
