apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisBuildPipeline
metadata:
  name: [[ .Project ]]
  labels:
    polaris-project: [[ .Project ]]
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  source:
    codecommitrepo: [[ .Project ]]
    branch: master
