apiVersion: polaris.synthesis.co.za/v1alpha1
kind: PolarisSourceRepository
metadata:
  name: {{ template "thischart.fullname" $ }}
  labels:
    polaris-project: [[ .Project ]]
    app: {{ template "thischart.name" $ }}
    chart: {{ template "thischart.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  name: [[ .Project ]]